name: Promotion Service CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout shared repo
        uses: actions/checkout@v4
        with:
          repository: ShopEcommerce/ecommerce_shop-shared
          path: shared

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Build Shared Library
        run: |
          cd shared
          npm install --cache .npm-cache
          npm run build
          npm pack --cache .npm-cache

      - name: Install Dependencies
        run: |
          npm install ./shared/teleshop-common-1.0.4.tgz --cache .npm-cache
          npm install --cache .npm-cache

      - name: Generate Prisma Client
        run: |
          npx prisma generate

      - name: Setup Postgres for tests
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: promotion_db
          postgresql user: postgres
          postgresql password: postgres
          postgresql host: localhost
          postgresql port: 5432

      - name: Run Database Migrations
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/promotion_db?schema=public
        run: |
          npm run prisma:migrate:deploy

      - name: Run Linter
        run: |
          npm run lint

      - name: Run Unit Tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/promotion_db?schema=public
        run: |
          npm run test:ci
